channels:
- uibcdf/label/dev
- uibcdf
- conda-forge
- ambermd
- defaults
dependencies:
- python
- numpy
- pyunitwizard
- sabueso
- mmtf-python
- pandas
- mdtraj
- mdanalysis
- openmm
- pdbfixer
- openmmtools
- biopython
- nglview
- parmed
- pytraj
- openopenmmreporters
- openmolecularsystems
