channels:
- uibcdf/label/dev
- uibcdf
- conda-forge
- ambermd
- default
dependencies:
- python
- numpy
- pyunitwizard
- pandas
- mdtraj
- mdanalysis
- openmm
- pdbfixer
- openmmtools
- biopython
- nglview
- parmed
- pytraj
