package:
  name: molsysmt
  version: 0.0.5

source:
  path: ../../

build:
  number: 1

requirements:
  build:
    - python  {{ python }}
    - setuptools
    - numpy 

  run:
    - python  {{ python }}
    - numpy
    - mdtraj
    - mdanalysis
    - openmm
    - openmmtools
    - biopython
    - nglview
    - pdbfixer
    - parmed
    - yank
    - jupyterlab
    - pytraj

about:
  home: https://uibcdf.org
  license: MIT License
  summary: ""
  description: |
    This toolkit library provides some useful classes, functions, pipes and wrappers daily used in the uibcdf lab when molecular systems and molecular dynamics are manipulated.
  dev_url: https://github.com/uibcdf/MolSysMT
  doc_url: https://uibcdf.org/MolSysMT
