package:
  name: molmodmt
  version: 0.0.2

source:
  path: ../../

build:
  number: 2

requirements:
  build:
    - python {{ python }}
    - setuptools
    - numpy

  run:
    - python  {{ python }}
    - numpy
    - mdtraj
    - mdanalysis
    - nglview
    - openmm
    - openmmtools
    - biopython
    - pdbfixer
    - parmed
    - yank
    - ambertools
    - jupyterlab

about:
  home: https://uibcdf.org
  license: MIT License
  summary: ""
  description: |
    This library provides some useful classes, functions, pipes and wrappers daily used in the uibcdf lab when molecular systems and molecular dynamics are manipulated.
  dev_url: https://github.com/uibcdf/MolModMT
  doc_url: https://uibcdf.org/MolModMT
